import random
print("_____________________________________________")
print()
print("          |    GUESS THE NUMBER    |  ")
print("          --------------------------")
print("_____________________________________________")
print()
print("--<>--<>--<>---<>--<>--<>--<>--<>--<>--<>--<>")
print("                |  LIMIT  |      ")
print("                -----------")
a=int(input("      Enter the starting number: "))
c=int(input("      Enter the ending number  : "))
b=c+1
num1=random.randrange(a,b)
print("--<>--<>--<>---<>--<>--<>--<>--<>--<>--<>--<>")
print("_____________________________________________")
print("                |  PLAYER 1 |   ")
print("                -------------  ")
print()
for i in range(1,100):
    choice1=int(input("Enter the choice number:"))
    if(num1>choice1):
        print(" the number is greater than ",choice1)
    elif(num1<choice1):
        print(" the number is less than    ", choice1)
    elif(num1==choice1):
        print()
        print("<>--<>--<>--<>--<>--<>--<>--<>--<>--<>")
        print(" ---------------------------------- ")   
        print(" |        congratulation          |")
        print(" |           player 1             |")
        print(" | You choosed the correct number |")
        print(" |_        the number is         _|") 
        print("                {}                 ".format(num1))
        print(" |-  Your have tried {} times     -|".format(i))
        print(" ---------------------------------- ")
        print("<>--<>--<>--<>--<>--<>--<>--<>--<>--<>")
        break
num2=random.randrange(a,b)
print("_____________________________________________")
print("                |  PLAYER 2 |   ")
print("                -------------  ")
print()
for j in range(1,100):
    choice2=int(input("Enter the choice number:"))
    if(num2>choice2):
        print(" the number is greater than ",choice2)
    elif(num2<choice2):
        print(" the number is less than    ",choice2)
    elif(num2==choice2):
        print()
        print("<>--<>--<>--<>--<>--<>--<>--<>--<>--<>")
        print(" ---------------------------------- ")   
        print(" |        congratulation          |")
        print(" |           player 2             |")
        print(" | You choosed the correct number |")
        print(" |_        the number is         _|") 
        print("                {}                 ".format(num2))
        print(" |-  Your have tried {} times     -|".format(j))
        print(" ---------------------------------- ")
        print("<>--<>--<>--<>--<>--<>--<>--<>--<>--<>")
        break
print("_____________________________________________")
print("_____________________________________________")
print()
if(i<j):
    print("             ------------------")
    print("             |  PLAYER 1 WINS |")
    print("-------------------------------------------")
    print("| better luck next time(PLAYER 2),to beat |")
    print("|            your opponent tries          |")
    print("-------------------------------------------")
elif(i>j):
    print("             ------------------")
    print("             |  PLAYER 2 WINS |")
    print("-------------------------------------------")
    print("| better luck next time(PLAYER 1),to beat |")
    print("|            your opponent tries          |")
    print("-------------------------------------------")
elif(i==j):
    print("             ------------------")
    print("             |      DRAW      |")
    print("-------------------------------------------")
    print("| better luck next time(PLAYER 1,2),Try to|")
    print("|               win the game              |")
    print("-------------------------------------------")
  
print("_____________________________________________")
print("_____________________________________________") 